<div align="left" style="background-color: #008080; padding: 20px 10px;">
<h3><b>IDEAS - Institute of Data Engineering, Analytics and Science Foundation</b></h3>
<p>Summer Internship Program 2026</p>
<hr style="width:100%;">
<h3><b>Project Title:</b> Used Car Price Prediction Using Regression Models</h3>
<h4>Project Notebook</h4>

<blockquote style="border-left: 4px solid #4285F4; padding-left: 15px;">
  <strong>Created by:</strong> Suprava Das<br>
  <strong>Designation:</strong> Associate Software Developer
</blockquote>
<hr style="width:100%;">
</div>

### Question 1: Import Packages and Load the Dataset (1 Mark)

Import `pandas` as `pd`. Download the dataset `used_cars.csv` from https://drive.google.com/drive/folders/1gieHICVDBbUKMZiSF4YRQMAJic-w50JM?usp=sharing. Load the dataset `used_cars.csv` into a DataFrame named `df`.
Create a copy of the DataFrame named `df1` to preserve the original data for future reference.

**Expected Output:** The code cell should execute without any errors.

In [1]:
# Answer Q1
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
import io

print("upload the 'used_cars.csv' file:")
uploaded = files.upload()

# used_cars.csv file is uploaded
for fn in uploaded.keys():
    print('file "{name}" with length {length} bytes'.format(
        name=fn, length=len(uploaded[fn])))
    csv_file_path = io.BytesIO(uploaded[fn])

# Load the dataset into a DataFrame named df
df = pd.read_csv(csv_file_path)

# Create a copy of the DataFrame named df1
df1 = df.copy()

# Display the first 5 rows of df to confirm
display(df.head())

Mounted at /content/drive
upload the 'used_cars.csv' file:

Saving used_cars.csv to used_cars.csv
file "used_cars.csv" with length 607822 bytes

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

### Question 2: Shuffle and Display the Dataset (1 Mark)

Shuffle the dataset `df1` using `.sample(frac=1, random_state=42)` to ensure the data is randomly distributed. Display the top 10 rows of the shuffled dataset.

**Expected Output:** A table showing the first 10 rows of the randomized DataFrame.

In [2]:
# Answer Q2

# Shuffle the df1 dataset
df1_shuffled = df1.sample(frac=1, random_state=42)

# Display the top 10 rows of the shuffled dataset
display(df1_shuffled.head(10))

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
2580,Lexus,IS 300 Base,2018,"50,992 mi.",Gasoline,260.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Gray,At least 1 accident or damage reported,Yes,"$28,000"
3660,Chevrolet,Impala Base,2004,"64,500 mi.",Gasoline,180.0HP 3.4L V6 Cylinder Engine Gasoline Fuel,A/T,Beige,Beige,None reported,Yes,"$5,900"
897,RAM,2500 SLT,2017,"86,000 mi.",Diesel,350.0HP 6.7L Straight 6 Cylinder Engine Diesel...,6-Speed A/T,Gray,Gray,At least 1 accident or damage reported,Yes,"$41,000"
2091,Mercedes-Benz,SL-Class SL 550,2013,"24,933 mi.",Gasoline,429.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Silver,Red,At least 1 accident or damage reported,Yes,"$40,250"
1044,Ford,Shelby GT350R Base,2018,"18,500 mi.",Gasoline,526.0HP 5.2L 8 Cylinder Engine Gasoline Fuel,M/T,Blue,Black,At least 1 accident or damage reported,Yes,"$77,999"
2320,GMC,Yukon SLT,2018,"85,500 mi.",Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,Yes,"$35,899"
465,Volvo,V60 Cross Country T5,2020,"10,500 mi.",Gasoline,250.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,None reported,Yes,"$36,000"
196,Nissan,Titan XD SV,2020,"10,001 mi.",Gasoline,5.6L V8 32V GDI DOHC,9-Speed Automatic,Black,Black,None reported,Yes,"$47,214"
3113,BMW,330 i,2005,"59,300 mi.",Gasoline,225.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,M/T,Red,Black,None reported,Yes,"$30,900"
3553,Lexus,RX 330 Base,2006,"110,250 mi.",Gasoline,230.0HP 3.3L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes,"$11,000"

### Question 3: Dataset Overview and Missing Values (2 Marks)

Print the total number of data points (rows) in the dataset `df1`. Then, find and print the number of null (missing) values present in each column.

**Expected Output:** The total row count and a Series showing the count of nulls per column.

In [3]:
# Answer Q3

# Print the total number of data points (rows) in df1
print(f"Total number of data points in df1: {len(df1)}")

# Find and print the number of null (missing) values present in each column
print("\nNumber of null values per column in df1:")
display(df1.isnull().sum())

Total number of data points in df1: 4009

Number of null values per column in df1:

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

### Question 4: Standardize Missing or Invalid Strings (2 Marks)

For all columns with an `object` (string) data type in `df1`, perform the following replacements to standardize missing data:
- Replace the specific character `'–'` with the string `'Unknown'`.
- Replace the string `'nan'` with `'Unknown'`.
- Replace any entirely empty strings or strings consisting only of whitespace with `'Unknown'`.

**Expected Output:** The code cell should execute without errors, standardizing the text data.

In [4]:
# Answer Q4
import numpy as np

# Get all object columns
object_columns = df1.select_dtypes(include='object').columns

for col in object_columns:
    # Replace '–' with 'Unknown'
    # Ensure conversion to string type first to handle mixed types gracefully
    df1[col] = df1[col].astype(str).str.replace('–', 'Unknown', regex=False)

    # Replace 'nan' string with 'Unknown'
    df1[col] = df1[col].str.replace('nan', 'Unknown', regex=False)

    # Replace empty strings or strings consisting only of whitespace with 'Unknown'
    # The regex r'^\s*$' matches strings that are either empty or contain only whitespace characters.
    df1[col] = df1[col].replace(r'^\s*$', 'Unknown', regex=True)

    # Finally, fill any remaining actual numpy.nan values that might exist with 'Unknown'
    # (though previous steps should convert them to string 'nan' then 'Unknown')
    df1[col] = df1[col].fillna('Unknown')

### Verification of Standardized String Data

Let's check a few `object` columns to confirm that '–', 'nan', and whitespace-only strings have been replaced with 'Unknown'.

In [5]:
# Display the first few rows of df1 to see the general impact
display(df1.head())

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,Unknown,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,Unknown,"$34,999"

In [6]:
# Select some 'object' type columns to inspect
# We'll take the first 10 object columns, or fewer if not available
columns_to_check = df1.select_dtypes(include='object').columns.tolist()[:10]

print("\nVerifying standardization in selected object columns:")
for col in columns_to_check:
    print(f"\nColumn: {col}")
    # Display unique values and their counts to see if 'Unknown' is present and old values are gone
    display(df1[col].value_counts(dropna=False).head(10))

Verifying standardization in selected object columns:

Column: brand

brand
Ford             386
BMW              375
Mercedes-Benz    315
Chevrolet        292
Porsche          201
Audi             200
Toyota           199
Lexus            163
Jeep             143
Land             130
Name: count, dtype: int64

Column: model

model
M3 Base               30
F-150 XLT             24
Corvette Base         22
1500 Laramie          18
Camaro 2SS            17
Wrangler Sport        17
Model Y Long Range    17
Mustang GT Premium    16
911 Carrera           16
M4 Base               15
Name: count, dtype: int64

Column: milage

milage
110,000 mi.    16
45,000 mi.     15
120,000 mi.    13
55,000 mi.     13
54,000 mi.     12
60,000 mi.     12
92,000 mi.     12
40,000 mi.     12
65,000 mi.     12
73,000 mi.     11
Name: count, dtype: int64

Column: fuel_type

fuel_type
Gasoline          3309
Unknown            215
Hybrid             194
E85 Flex Fuel      139
Diesel             116
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

Column: engine

engine
2.0L I4 16V GDI DOHC Turbo                               52
355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel             48
420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel             47
Unknown                                                  45
300.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel    44
240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel             42
285.0HP 3.6L V6 Cylinder Engine Gasoline Fuel            40
5.7L V8 16V MPFI OHV                                     29
340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel            28
3.6L V6 24V MPFI DOHC                                    28
Name: count, dtype: int64

Column: transmission

transmission
A/T                               1037
8-Speed A/T                        406
Transmission w/Dual Shift Mode     398
6-Speed A/T                        362
6-Speed M/T                        248
Automatic                          237
7-Speed A/T                        209
8-Speed Automatic                  176
10-Speed A/T                       119
5-Speed A/T                         86
Name: count, dtype: int64

Column: ext_col

ext_col
Black     905
White     816
Gray      496
Silver    374
Blue      349
Red       261
Green      74
Brown      43
Gold       42
Beige      38
Name: count, dtype: int64

Column: int_col

int_col
Black        2025
Beige         538
Gray          472
Brown         157
Unknown       133
White         127
Red           126
Jet Black      59
Ebony          44
Blue           29
Name: count, dtype: int64

Column: accident

accident
None reported                             2910
At least 1 accident or damage reported     986
Unknown                                    113
Name: count, dtype: int64

Column: clean_title

clean_title
Yes        3413
Unknown     596
Name: count, dtype: int64

### Question 5: Feature Engineering - Car Age (1 Mark)

Create a new column named `car_age` in `df1` by calculating the age of each car. You can do this by subtracting the `model_year` from the current year (use `2026` as the current year).
After calculating the age, drop the original `model_year` column from the DataFrame.

**Expected Output:** The code cell should execute without errors.

In [7]:
# Answer Q5

# Create a new column named car_age and drop model_year, if model_year exists
import pandas as pd # Ensure pandas is imported for DataFrame operations

if 'model_year' in df1.columns:
    # Using 2026 as the current year
    df1['car_age'] = 2026 - df1['model_year']

    # Drop the original model_year column from the DataFrame
    df1 = df1.drop('model_year', axis=1)
    print("Car age calculated and 'model_year' column dropped.")
else:
    print("Column 'model_year' not found in df1. It might have already been processed or renamed.")

# The problem states the code should execute without errors, no display is explicitly requested.

Car age calculated and 'model_year' column dropped.

In [8]:
 #Display current columns of df1
print("Columns in df1:")
print(df1.columns.tolist())

# Display the first few rows of df1 to see the impact
print("\nFirst 5 rows of df1 (showing 'car_age' instead of 'model_year'):")
display(df1.head())

Columns in df1:
['brand', 'model', 'milage', 'fuel_type', 'engine', 'transmission', 'ext_col', 'int_col', 'accident', 'clean_title', 'price', 'car_age']

First 5 rows of df1 (showing 'car_age' instead of 'model_year'):

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,Ford,Utility Police Interceptor Base,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,Unknown,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,Unknown,"$34,999",5

In [9]:
# Display the first 10 rows of df1
display(df1.head(10))

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,Ford,Utility Police Interceptor Base,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,Unknown,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,Unknown,"$34,999",5
5,Acura,ILX 2.4L,"136,397 mi.",Gasoline,2.4 Liter,F,Silver,Ebony.,None reported,Unknown,"$14,798",10
6,Audi,S3 2.0T Premium Plus,"84,000 mi.",Gasoline,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Black,None reported,Yes,"$31,000",9
7,BMW,740 iL,"242,000 mi.",Gasoline,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Green,None reported,Yes,"$7,300",25
8,Lexus,RC 350 F Sport,"23,436 mi.",Gasoline,311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,"$41,927",5
9,Tesla,Model X Long Range Plus,"34,000 mi.",Unknown,534.0HP Electric Motor Electric Fuel System,A/T,Black,Black,None reported,Yes,"$69,950",6

### Question 6: Format Numeric Columns (1 Mark)

Clean the following two columns so they can be used as numbers:
1. **milage:** Remove the string `' mi.'` and any commas (`,`), then convert the column to integers.
2. **price:** Remove currency symbols (`$`) and any commas (`,`), then convert the column to floats.

**Expected Output:** The code cell should execute without errors, changing both columns to numeric types.

In [ ]:
# Answer Q6

# 1. Clean and convert 'milage' column to integers
# Remove ' mi.' and commas, then convert to numeric
df1['milage'] = df1['milage'].astype(str).str.replace(' mi.', '', regex=False)
df1['milage'] = df1['milage'].astype(str).str.replace(',', '', regex=False)
df1['milage'] = pd.to_numeric(df1['milage'], errors='coerce').astype('Int64') # Using 'Int64' to allow for NaN if coercion fails

# 2. Clean and convert 'price' column to floats
# Remove currency symbols ($) and commas, then convert to numeric
df1['price'] = df1['price'].astype(str).str.replace('$', '', regex=False)
df1['price'] = df1['price'].astype(str).str.replace(',', '', regex=False)
df1['price'] = pd.to_numeric(df1['price'], errors='coerce')

# Display data types to confirm changes
print("Data types after cleaning 'milage' and 'price':")
display(df1[['milage', 'price']].dtypes)

# Display head to see impact (optional)
print("\nFirst 5 rows after cleaning 'milage' and 'price':")
display(df1.head())

### Question 7: Handle Low-Frequency Categories (2 Marks)

Some categorical columns have too many rare values. For both the `transmission` and `ext_col` columns, group categories that appear in **less than 1%** of the total dataset into a new category called `'others'`.
Additionally, drop the `clean_title` column entirely as it provides little variance.

**Expected Output:** The code cell should execute without errors.

In [10]:
 # Answer Q7

# Define a function to group low-frequency categories
def group_low_frequency_categories(df, column, threshold=0.01):
    total_rows = len(df)
    # Calculate value counts and their proportion
    value_counts = df[column].value_counts()
    proportions = value_counts / total_rows

    # Identify categories to be grouped as 'others'
    low_frequency_categories = proportions[proportions < threshold].index

    # Replace low-frequency categories with 'others'
    df[column] = df[column].replace(low_frequency_categories, 'others')
    return df

# Apply the function to 'transmission' column
df1 = group_low_frequency_categories(df1, 'transmission', threshold=0.01)

# Apply the function to 'ext_col' column
df1 = group_low_frequency_categories(df1, 'ext_col', threshold=0.01)

# Drop the 'clean_title' column, if it exists
if 'clean_title' in df1.columns:
    df1 = df1.drop('clean_title', axis=1)
    print("'clean_title' column dropped.")


print("DataFrame after handling low-frequency categories and potentially dropping 'clean_title':")
# Display unique values and their counts for 'transmission' and 'ext_col' to verify (optional)
print("\nUnique values and counts for 'transmission' after grouping:")
display(df1['transmission'].value_counts())
print("\nUnique values and counts for 'ext_col' after grouping:")
display(df1['ext_col'].value_counts())

# Display info to confirm 'clean_title' is dropped and types are still correct (optional)
print("\nDataFrame info after changes:")
df1.info()

'clean_title' column dropped.
DataFrame after handling low-frequency categories and potentially dropping 'clean_title':

Unique values and counts for 'transmission' after grouping:

transmission
A/T                               1037
8-Speed A/T                        406
Transmission w/Dual Shift Mode     398
6-Speed A/T                        362
6-Speed M/T                        248
Automatic                          237
others                             224
7-Speed A/T                        209
8-Speed Automatic                  176
10-Speed A/T                       119
5-Speed A/T                         86
9-Speed A/T                         74
6-Speed Automatic                   73
4-Speed A/T                         72
1-Speed A/T                         64
CVT Transmission                    62
5-Speed M/T                         59
10-Speed Automatic                  56
9-Speed Automatic                   47
Name: count, dtype: int64

Unique values and counts for 'ext_col' after grouping:

ext_col
Black     905
White     816
others    649
Gray      496
Silver    374
Blue      349
Red       261
Green      74
Brown      43
Gold       42
Name: count, dtype: int64

DataFrame info after changes:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   milage        4009 non-null   object
 3   fuel_type     4009 non-null   object
 4   engine        4009 non-null   object
 5   transmission  4009 non-null   object
 6   ext_col       4009 non-null   object
 7   int_col       4009 non-null   object
 8   accident      4009 non-null   object
 9   price         4009 non-null   object
 10  car_age       4009 non-null   int64
dtypes: int64(1), object(10)
memory usage: 344.7+ KB

### Question 8: Remove Outliers and Apply Label Encoding (2 Marks)

Remove price outliers by filtering `df1` to keep only rows where the `price` is **below the 99th percentile**.
Next, import `LabelEncoder` from `sklearn.preprocessing` and apply it to convert all remaining categorical (`object`) columns into numerical values.

**Expected Output:** The code cell should execute without errors.

In [21]:
# Answer Q8
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Re-clean and convert 'milage' and 'price' columns to ensure they are numeric
# This step is added as a safeguard in case previous cleaning steps did not persist or were incomplete.

# For 'milage': Remove ' mi.' and commas, then convert to numeric
# First, ensure it's string to apply string methods reliably
df1.loc[:, 'milage'] = df1['milage'].astype(str).str.replace(' mi.', '', regex=False)
df1.loc[:, 'milage'] = df1['milage'].astype(str).str.replace(',', '', regex=False)
df1.loc[:, 'milage'] = pd.to_numeric(df1['milage'], errors='coerce').astype('Int64') # Using 'Int64' to allow for NaN if coercion fails

# For 'price': Remove currency symbols ($) and commas, then convert to numeric
# First, ensure it's string to apply string methods reliably
df1.loc[:, 'price'] = df1['price'].astype(str).str.replace('$', '', regex=False)
df1.loc[:, 'price'] = df1['price'].astype(str).str.replace(',', '', regex=False)
df1.loc[:, 'price'] = pd.to_numeric(df1['price'], errors='coerce') # Converts to float64 by default if there are non-integer values or NaNs

# 1. Remove price outliers by filtering df1 to keep only rows where the price is below the 99th percentile
# Calculate the 99th percentile of the 'price' column
price_99th_percentile = df1['price'].quantile(0.99)

# Filter the DataFrame to keep only rows where price is below the 99th percentile
df1 = df1[df1['price'] < price_99th_percentile]

print(f"DataFrame shape after removing price outliers: {df1.shape}")

# 2. Apply LabelEncoder to convert all remaining categorical (object) columns into numerical values
# Identify remaining object columns
object_columns_to_encode = df1.select_dtypes(include='object').columns.tolist()

# Explicitly remove 'price' from the list of columns to be label encoded
# as 'price' is intended to be a numeric target variable, not a categorical feature.
if 'price' in object_columns_to_encode:
    print("Removing 'price' from the list of columns to be label encoded as it should be numeric.")
    object_columns_to_encode.remove('price')

# Initialize LabelEncoder
le = LabelEncoder()

for col in object_columns_to_encode:
    # Apply Label Encoding to each object column
    df1.loc[:, col] = le.fit_transform(df1[col])
    print(f"Column '{col}' label encoded.")

print("\nDataFrame info after outlier removal and label encoding:")
df1.info()
print("\nFirst 5 rows after outlier removal and label encoding:")
display(df1.head())

DataFrame shape after removing price outliers: (3928, 11)
Column 'price' label encoded.

DataFrame info after label encoding:
<class 'pandas.core.frame.DataFrame'>
Index: 3928 entries, 0 to 4008
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         3928 non-null   int64
 1   model         3928 non-null   int64
 2   milage        3928 non-null   Int64
 3   fuel_type     3928 non-null   int64
 4   engine        3928 non-null   int64
 5   transmission  3928 non-null   int64
 6   ext_col       3928 non-null   int64
 7   int_col       3928 non-null   int64
 8   accident      3928 non-null   int64
 9   price         3928 non-null   object
 10  car_age       3928 non-null   int64
dtypes: Int64(1), int64(9), object(1)
memory usage: 372.1+ KB

First 5 rows after outlier removal and label encoding:

/tmp/ipykernel_6269/4112317960.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['10300' '38005' '54598' ... '90998' '62999' '40000']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.loc[:, 'price'] = df1['price'].astype(str).str.replace('$', '', regex=False)

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price,car_age
0,13,1725,51000,1,578,6,0,14,0,141,13
1,18,1166,34742,2,563,11,9,65,0,760,5
2,26,1307,22372,2,539,15,1,14,1,1059,4
3,19,1224,88900,3,721,9,0,14,1,254,11
4,3,1207,9835,2,199,11,9,14,1,690,5

### Question 9: Train-Test Split (1 Mark)

Define the `price` column as your target variable (`y`) and separate the remaining columns to form the feature set (`X`).
Split the features and target into training and testing datasets using an 80:20 ratio (`test_size=0.2`) and set `random_state=42`. Print the shapes of the resulting `X_train` and `X_test`.

**Expected Output:** A printout of the dimensions (shape) for the training and testing feature sets.

In [16]:
# Answer Q9
from sklearn.model_selection import train_test_split

# Define the 'price' column as the target variable (y)
y = df1['price']

# Separate the remaining columns to form the feature set (X)
X = df1.drop('price', axis=1)

# Split the features and target into training and testing datasets
# using an 80:20 ratio (test_size=0.2) and set random_state=42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shapes of the resulting X_train and X_test
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (3174, 10)
Shape of X_test: (794, 10)
Shape of y_train: (3174,)
Shape of y_test: (794,)

### Question 10: Model Training and Evaluation (4 Marks)

Import `RandomForestRegressor` from `sklearn.ensemble`, and `r2_score`, `mean_squared_error`, `mean_absolute_error` from `sklearn.metrics`.
Train the Random Forest model (with `n_estimators=100`, `random_state=42`) on the training data. Predict the prices for the test data and evaluate the model by printing the R² Score, MSE, and MAE.

**Expected Output:** Three numeric values representing the R² score, Mean Squared Error, and Mean Absolute Error of the model.

In [17]:
# Answer Q10
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Initialize and train the Random Forest model
# n_estimators=100, random_state=42
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict prices for the test data
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

# Print the evaluation metrics
print(f"R² Score: {r2:.4f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")

R² Score: 0.7269
Mean Squared Error (MSE): 321359337.79
Mean Absolute Error (MAE): 9500.19

### Question 11: Load MNIST Data (3 Marks)

Load the MNIST dataset using `sklearn.datasets.load_digits`. Separate the dataset into features (`X`) and target labels (`y`).
Print the shape of the features and the target arrays.

**Expected Output:** The shape of `X` and `y`.

In [18]:
# Answer Q11
from sklearn.datasets import load_digits

# Load the MNIST dataset
digits = load_digits()

# Separate features (X) and target labels (y)
X = digits.data
y = digits.target

# Print the shape of the features and the target arrays
print(f"Shape of features (X): {X.shape}")
print(f"Shape of target labels (y): {y.shape}")

Shape of features (X): (1797, 64)
Shape of target labels (y): (1797,)

### Question 12: K-Means Clustering (5 Marks)

Import `KMeans` from `sklearn.cluster`. Initialize and fit the K-Means clustering model on the MNIST features (`X`).
Since we know there are 10 digits (0-9), set the number of clusters to 10. Assign the cluster labels to a variable `kmeans_labels`.

**Expected Output:** A successfully fitted K-Means model and the cluster labels array.

In [19]:
# Answer Q12
from sklearn.cluster import KMeans

# Initialize KMeans with 10 clusters (for digits 0-9)
# Set random_state for reproducibility
kmeans = KMeans(n_clusters=10, random_state=42, n_init='auto') # n_init='auto' is recommended for newer scikit-learn versions

# Fit the KMeans model to the features (X)
kmeans.fit(X)

# Assign the cluster labels to kmeans_labels
kmeans_labels = kmeans.labels_

print(f"Shape of kmeans_labels: {kmeans_labels.shape}")
print("First 10 cluster labels:")
display(kmeans_labels[:10])

Shape of kmeans_labels: (1797,)
First 10 cluster labels:

array([5, 7, 7, 6, 4, 9, 2, 0, 8, 9], dtype=int32)

### Question 13: F1 Score Evaluation for Clustering (5 Marks)

Evaluate the clustering performance using the F1 score. Since K-Means assigns arbitrary cluster labels, you will first need to map each cluster label to the most frequent true label in that cluster.
After mapping the labels, calculate and print the macro-averaged F1 score using `sklearn.metrics.f1_score`.

**Expected Output:** The calculated F1 score of the clustering.

In [20]:
# Answer Q13
from sklearn.metrics import f1_score
import numpy as np
from scipy.stats import mode

# Create a mapping from cluster label to true label
# Initialize an empty dictionary to store the mapping
labels_map = {}

# Iterate through each unique cluster label found by KMeans
for i in np.unique(kmeans_labels):
    # Find the true labels (y) for all data points that were assigned to cluster i
    # Then, find the most frequent true label among these points
    # mode()[0][0] returns the most frequent element
    most_frequent_true_label = mode(y[kmeans_labels == i], keepdims=False)[0]
    # Store this mapping: cluster_label -> most_frequent_true_label
    labels_map[i] = most_frequent_true_label

# Apply the mapping to the kmeans_labels to get the predicted labels that align with true labels
predicted_labels = np.array([labels_map[label] for label in kmeans_labels])

# Calculate the macro-averaged F1 score
f1 = f1_score(y, predicted_labels, average='macro')

# Print the F1 score
print(f"Macro-averaged F1 Score for K-Means Clustering: {f1:.4f}")

Macro-averaged F1 Score for K-Means Clustering: 0.8628